import { Participant } from './types';

// Enhanced mock participants with more realistic data
export const mockParticipants: Participant[] = [
  // {
  //   id: 'you',
  //   name: 'You',
  //   isVideoOn: true,
  //   isAudioOn: true,
  //   connectionQuality: 'good',
  //   isYou: true,
  //   isSpeaking: false,
  //   joinedAt: new Date(Date.now() - 600000).toISOString(),
  // },
  // {
  //   id: 'alice',
  //   name: 'Alice Johnson',
  //   isVideoOn: true,
  //   isAudioOn: true,
  //   connectionQuality: 'good',
  //   isHost: true,
  //   isSpeaking: false,
  //   joinedAt: new Date(Date.now() - 480000).toISOString(),
  // },
  // {
  //   id: 'bob',
  //   name: 'Bob Smith',
  //   isVideoOn: false,
  //   isAudioOn: true,
  //   connectionQuality: 'poor',
  //   isHandRaised: true,
  //   isSpeaking: true,
  //   joinedAt: new Date(Date.now() - 360000).toISOString(),
  // },
  // {
  //   id: 'carol',
  //   name: 'Carol Davis',
  //   isVideoOn: true,
  //   isAudioOn: false,
  //   connectionQuality: 'good',
  //   isSpeaking: false,
  //   joinedAt: new Date(Date.now() - 240000).toISOString(),
  // },
  // {
  //   id: 'david',
  //   name: 'David Wilson',
  //   isVideoOn: true,
  //   isAudioOn: true,
  //   connectionQuality: 'good',
  //   isScreenSharing: true,
  //   isSpeaking: false,
  //   joinedAt: new Date(Date.now() - 120000).toISOString(),
  // },
  // {
  //   id: 'eva',
  //   name: 'Eva Brown',
  //   isVideoOn: true,
  //   isAudioOn: true,
  //   connectionQuality: 'disconnected',
  //   isSpeaking: false,
  //   joinedAt: new Date(Date.now() - 60000).toISOString(),
  // },
];
